GSoutenance/Models/Pfe_Etudiant.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GSoutenance.Models
{
    public class Pfe_Etudiant
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("Pfe")]
        public int PFEID { get; set; }
         public virtual Pfe? Pfe { get; set; }

        [ForeignKey("Etudiant")]
        public int EtudiantId { get; set; }
        public virtual Etudiant? Etudiant { get; set; }
     
    }
}

GSoutenance/Controllers/Pfe_EtudiantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GSoutenance.Models;

namespace GSoutenance.Controllers
{
    public class Pfe_EtudiantController : Controller
    {
        private readonly SoutenanceContext _context;

        public Pfe_EtudiantController(SoutenanceContext context)
        {
            _context = context;
        }

        // GET: Pfe_Etudiant
        public async Task<IActionResult> Index()
        {
            var soutenanceContext = _context.Pfe_Etudiant.Include(p => p.Etudiant).Include(p => p.Pfe);
            return View(await soutenanceContext.ToListAsync());
        }



        public async Task<IActionResult> Search(string searchString)
        {
            var query = _context.Pfe_Etudiant
                .Include(pe => pe.Etudiant)
                .Include(pe => pe.Pfe)
                .Where(pe => pe.Etudiant != null); // Assurez-vous que l'étudiant n'est pas null

            if (!string.IsNullOrEmpty(searchString))
            {
                // Modifiez la condition pour rechercher à la fois le nom et le prénom
                query = query.Where(pe =>
                    pe.Etudiant.Nom.Contains(searchString) ||
                    pe.Pfe.titre.Contains(searchString));
            }

            var pfeEtudiants = await query.ToListAsync();
            return View("Index", pfeEtudiants);
        }






        // GET: Pfe_Etudiant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pfe_Etudiant = await _context.Pfe_Etudiant
                .Include(p => p.Etudiant)
                .Include(p => p.Pfe)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pfe_Etudiant == null)
            {
                return NotFound();
            }

            return View(pfe_Etudiant);
        }

        // GET: Pfe_Etudiant/Create
        public IActionResult Create()
        {
            ViewData["EtudiantId"] = new SelectList(_context.Etudiant, "EtudiantId", "Nom");
            ViewData["PFEID"] = new SelectList(_context.Pfe, "PFEID", "desc");
            return View();
        }

        // POST: Pfe_Etudiant/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PFEID,EtudiantId")] Pfe_Etudiant pfe_Etudiant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pfe_Etudiant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EtudiantId"] = new SelectList(_context.Etudiant, "EtudiantId", "Nom", pfe_Etudiant.EtudiantId);
            ViewData["PFEID"] = new SelectList(_context.Pfe, "PFEID", "desc", pfe_Etudiant.PFEID);
            return View(pfe_Etudiant);
        }

        // GET: Pfe_Etudiant/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pfe_Etudiant = await _context.Pfe_Etudiant.FindAsync(id);
            if (pfe_Etudiant == null)
            {
                return NotFound();
            }
            ViewData["EtudiantId"] = new SelectList(_context.Etudiant, "EtudiantId", "Nom", pfe_Etudiant.EtudiantId);
            ViewData["PFEID"] = new SelectList(_context.Pfe, "PFEID", "desc", pfe_Etudiant.PFEID);
            return View(pfe_Etudiant);
        }

        // POST: Pfe_Etudiant/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PFEID,EtudiantId")] Pfe_Etudiant pfe_Etudiant)
        {
            if (id != pfe_Etudiant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pfe_Etudiant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Pfe_EtudiantExists(pfe_Etudiant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EtudiantId"] = new SelectList(_context.Etudiant, "EtudiantId", "Nom", pfe_Etudiant.EtudiantId);
            ViewData["PFEID"] = new SelectList(_context.Pfe, "PFEID", "desc", pfe_Etudiant.PFEID);
            return View(pfe_Etudiant);
        }

        // GET: Pfe_Etudiant/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pfe_Etudiant = await _context.Pfe_Etudiant
                .Include(p => p.Etudiant)
                .Include(p => p.Pfe)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pfe_Etudiant == null)
            {
                return NotFound();
            }

            return View(pfe_Etudiant);
        }

        // POST: Pfe_Etudiant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pfe_Etudiant = await _context.Pfe_Etudiant.FindAsync(id);
            if (pfe_Etudiant != null)
            {
                _context.Pfe_Etudiant.Remove(pfe_Etudiant);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Pfe_EtudiantExists(int id)
        {
            return _context.Pfe_Etudiant.Any(e => e.Id == id);
        }
    }
}

GSoutenance/Views/Pfe_Etudiant/Create.cshtml
@model GSoutenance.Models.Pfe_Etudiant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pfe_Etudiant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PFEID" class="control-label"></label>
                <select asp-for="PFEID" class ="form-control" asp-items="ViewBag.PFEID"></select>
            </div>
            <div class="form-group">
                <label asp-for="EtudiantId" class="control-label"></label>
                <select asp-for="EtudiantId" class ="form-control" asp-items="ViewBag.EtudiantId"></select>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Pfe_Etudiant/Delete.cshtml
@model GSoutenance.Models.Pfe_Etudiant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pfe_Etudiant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etudiant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etudiant.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pfe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pfe.desc)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
    </form>
</div>

GSoutenance/Views/Pfe_Etudiant/Details.cshtml
@model GSoutenance.Models.Pfe_Etudiant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pfe_Etudiant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etudiant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etudiant.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pfe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pfe.desc)
        </dd>
    </dl>
</div>
<div style="margin-top: 20px;">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-outline-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

GSoutenance/Views/Pfe_Etudiant/Edit.cshtml
@model GSoutenance.Models.Pfe_Etudiant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pfe_Etudiant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PFEID" class="control-label"></label>
                <select asp-for="PFEID" class="form-control" asp-items="ViewBag.PFEID"></select>
                <span asp-validation-for="PFEID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EtudiantId" class="control-label"></label>
                <select asp-for="EtudiantId" class="form-control" asp-items="ViewBag.EtudiantId"></select>
                <span asp-validation-for="EtudiantId" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Save" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Pfe_Etudiant/Index.cshtml
@model IEnumerable<GSoutenance.Models.Pfe_Etudiant>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">Table Des Pfe_Etudiant</h1>
<form asp-controller="Pfe_Etudiant" asp-action="Search" method="get" class="d-flex search-from">
    <input class="form-control" type="text" placeholder="Search" name="searchString">
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<p style="margin-top: 20px;">
    <a asp-action="Create" class="btn btn-outline-secondary">Ajouter NV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Etudiant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pfe)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.Etudiant.EtudiantId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Etudiant.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pfe.titre)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Modifier</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>