GSoutenance/Models/Etudiant.cs
using System.ComponentModel.DataAnnotations;

namespace GSoutenance.Models
{
    public class Etudiant
    {
        [Key]
        [Display(Name = "ID")]
        public int EtudiantId { get; set; }
        [Required(ErrorMessage = "Nom Obligatoire")]
        [StringLength(30, MinimumLength = 3)]
        public string? Nom { get; set; }

        [Required(ErrorMessage = "Prénom Obligatoire")]
        [StringLength(30, MinimumLength = 3)]
        public string? Prenom { get; set; }

        [Display(Name = "Date De Naissance")]
        public DateTime DateN { get; set; }
        public virtual ICollection<Pfe_Etudiant>? Pfe_etudiants { get; set; }
    }
}

GSoutenance/Controllers/EtudiantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GSoutenance.Models;

namespace GSoutenance.Controllers
{
    public class EtudiantsController : Controller
    {
        private readonly SoutenanceContext _context;

        public EtudiantsController(SoutenanceContext context)
        {
            _context = context;
        }

        // GET: Etudiants

        public async Task<IActionResult> Index()
        {
            return View(await _context.Etudiant.ToListAsync());
        }





        public async Task<IActionResult> Search(string searchString)
        {
            var query = _context.Etudiant.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                query = query.Where(e => e.Nom.Contains(searchString)
                                      || e.Prenom.Contains(searchString));
            }

            var etudiants = await query.ToListAsync();
            return View("Index", etudiants);
        }
    







    // GET: Etudiants/Details/5
    public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var etudiant = await _context.Etudiant
                .FirstOrDefaultAsync(m => m.EtudiantId == id);
            if (etudiant == null)
            {
                return NotFound();
            }

            return View(etudiant);
        }

        // GET: Etudiants/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Etudiants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EtudiantId,Nom,Prenom,DateN")] Etudiant etudiant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(etudiant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(etudiant);
        }

        // GET: Etudiants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var etudiant = await _context.Etudiant.FindAsync(id);
            if (etudiant == null)
            {
                return NotFound();
            }
            return View(etudiant);
        }

        // POST: Etudiants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EtudiantId,Nom,Prenom,DateN")] Etudiant etudiant)
        {
            if (id != etudiant.EtudiantId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(etudiant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EtudiantExists(etudiant.EtudiantId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(etudiant);
        }

        // GET: Etudiants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var etudiant = await _context.Etudiant
                .FirstOrDefaultAsync(m => m.EtudiantId == id);
            if (etudiant == null)
            {
                return NotFound();
            }

            return View(etudiant);
        }

        // POST: Etudiants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var etudiant = await _context.Etudiant.FindAsync(id);
            if (etudiant != null)
            {
                _context.Etudiant.Remove(etudiant);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EtudiantExists(int id)
        {
            return _context.Etudiant.Any(e => e.EtudiantId == id);
        }
    }
}

GSoutenance/Views/Etudiants/Create.cshtml
@model GSoutenance.Models.Etudiant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Etudiant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateN" class="control-label"></label>
                <input asp-for="DateN" class="form-control" />
                <span asp-validation-for="DateN" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Etudiants/Delete.cshtml
@model GSoutenance.Models.Etudiant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Etudiant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateN)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EtudiantId" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
    </form>
</div>

GSoutenance/Views/Etudiants/Details.cshtml
@model GSoutenance.Models.Etudiant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Etudiant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateN)
        </dd>
    </dl>
</div>
<div style="margin-top: 20px;">
    <a asp-action="Edit" asp-route-id="@Model?.EtudiantId" class="btn btn-outline-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

GSoutenance/Views/Etudiants/Edit.cshtml
@model GSoutenance.Models.Etudiant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Etudiant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EtudiantId" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateN" class="control-label"></label>
                <input asp-for="DateN" class="form-control" />
                <span asp-validation-for="DateN" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Save" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Etudiants/Index.cshtml
@model IEnumerable<GSoutenance.Models.Etudiant>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">Table d'Etudiant</h1>

<form asp-controller="Etudiants" asp-action="Search" method="get" class="d-flex">
    <input class="form-control me-sm-2" type="search" placeholder="Search" name="searchString">
    <button type="submit" class="btn btn-primary">Search</button>
</form>


<p style="margin-top: 20px;">
    <a asp-action="Create" class="btn btn-outline-secondary">Ajouter NV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EtudiantId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateN)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EtudiantId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateN)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.EtudiantId" class="btn btn-info">Modifier</a> |
                    <a asp-action="Details" asp-route-id="@item.EtudiantId" class="btn btn-warning">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.EtudiantId" class="btn btn-danger">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>