GSoutenance/Models/Ensignant.cs
using System.ComponentModel.DataAnnotations;

namespace GSoutenance.Models
{
    public class Ensignant
    {
        [Key]
        [Display(Name = "ID")]
        public int EncadreurID { get; set; }

        [Required(ErrorMessage = "Nom Obligatoire")]
        [StringLength(30, MinimumLength = 3)]
        public string? Nom { get; set; }

        [Required(ErrorMessage = "Prénom Obligatoire")]
        [StringLength(30, MinimumLength = 3)]
        public string? Prenom { get; set; }

        public virtual ICollection<Pfe>? Pfes { get; set; }
    }
}

GSoutenance/Controllers/EnsignantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GSoutenance.Models;

namespace GSoutenance.Controllers
{
    public class EnsignantsController : Controller
    {
        private readonly SoutenanceContext _context;

        public EnsignantsController(SoutenanceContext context)
        {
            _context = context;
        }

        // GET: Ensignants
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ensignant.ToListAsync());
        }




        public async Task<IActionResult> Search(string searchString)
        {
            var query = _context.Ensignant.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                query = query.Where(e => e.Nom.Contains(searchString)
                                      || e.Prenom.Contains(searchString));
            }

            var Ensignants = await query.ToListAsync();
            return View("Index", Ensignants);
        }








        // GET: Ensignants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ensignant = await _context.Ensignant
                .FirstOrDefaultAsync(m => m.EncadreurID == id);
            if (ensignant == null)
            {
                return NotFound();
            }

            return View(ensignant);
        }

        // GET: Ensignants/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ensignants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EncadreurID,Nom,Prenom")] Ensignant ensignant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ensignant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ensignant);
        }

        // GET: Ensignants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ensignant = await _context.Ensignant.FindAsync(id);
            if (ensignant == null)
            {
                return NotFound();
            }
            return View(ensignant);
        }

        // POST: Ensignants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EncadreurID,Nom,Prenom")] Ensignant ensignant)
        {
            if (id != ensignant.EncadreurID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ensignant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnsignantExists(ensignant.EncadreurID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ensignant);
        }

        // GET: Ensignants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ensignant = await _context.Ensignant
                .FirstOrDefaultAsync(m => m.EncadreurID == id);
            if (ensignant == null)
            {
                return NotFound();
            }

            return View(ensignant);
        }

        // POST: Ensignants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ensignant = await _context.Ensignant.FindAsync(id);
            if (ensignant != null)
            {
                _context.Ensignant.Remove(ensignant);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnsignantExists(int id)
        {
            return _context.Ensignant.Any(e => e.EncadreurID == id);
        }
    }
}

GSoutenance/Views/Ensignants/Create.cshtml
@model GSoutenance.Models.Ensignant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ensignant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Ensignants/Delete.cshtml
@model GSoutenance.Models.Ensignant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ensignant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EncadreurID" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
    </form>
</div>

GSoutenance/Views/Ensignants/Details.cshtml
@model GSoutenance.Models.Ensignant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ensignant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
    </dl>
</div>
<div style="margin-top: 20px;">
    <a asp-action="Edit" asp-route-id="@Model?.EncadreurID" class="btn btn-outline-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

GSoutenance/Views/Ensignants/Edit.cshtml
@model GSoutenance.Models.Ensignant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ensignant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EncadreurID" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Save" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Ensignants/Index.cshtml
@model IEnumerable<GSoutenance.Models.Ensignant>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">Table d'Ensignant</h1>
<form asp-controller="Ensignants" asp-action="Search" method="get" class="d-flex search-from">
    <input class="form-control" type="text" placeholder="Search" name="searchString">
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<p style="margin-top: 20px;">
    <a asp-action="Create" class="btn btn-outline-secondary">Ajouter NV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EncadreurID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.EncadreurID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.EncadreurID" class="btn btn-info">Modifier</a> |
                    <a asp-action="Details" asp-route-id="@item.EncadreurID" class="btn btn-warning">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.EncadreurID" class="btn btn-danger">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>