GSoutenance/Models/Societe.cs
using System.ComponentModel.DataAnnotations;

namespace GSoutenance.Models
{
    public class Societe
    {
        [Key]
        [Display(Name = "ID")]
        public int SocieteID { get; set; }

        [Display(Name = "Nom Societe")]
        [Required, StringLength(30, MinimumLength = 3)]
        public string? LibSociete { get; set; }

        [Required(ErrorMessage = "Adresse Obligatoire")]
        public string? Adresse { get; set; }

        [Required(ErrorMessage = "Tel Obligatoire")]
        [Range(99999999,99999999, ErrorMessage = "Le numéro de téléphone doit comporter obligatoire 8 chiffres.")]
        public int Tel { get; set; }

        public virtual ICollection<Pfe>? Pfes { get; set; }
    }
}

GSoutenance/Controllers/SocietesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GSoutenance.Models;

namespace GSoutenance.Controllers
{
    public class SocietesController : Controller
    {
        private readonly SoutenanceContext _context;

        public SocietesController(SoutenanceContext context)
        {
            _context = context;
        }

        // GET: Societes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Societe.ToListAsync());
        }




        public async Task<IActionResult> Search(string searchString)
        {
            var query = _context.Societe.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                query = query.Where(e => e.LibSociete.Contains(searchString)
                                      || e.Adresse.Contains(searchString));
            }

            var Societes = await query.ToListAsync();
            return View("Index", Societes);
        }










        // GET: Societes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var societe = await _context.Societe
                .FirstOrDefaultAsync(m => m.SocieteID == id);
            if (societe == null)
            {
                return NotFound();
            }

            return View(societe);
        }

        // GET: Societes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Societes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SocieteID,LibSociete,Adresse,Tel")] Societe societe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(societe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(societe);
        }

        // GET: Societes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var societe = await _context.Societe.FindAsync(id);
            if (societe == null)
            {
                return NotFound();
            }
            return View(societe);
        }

        // POST: Societes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SocieteID,LibSociete,Adresse,Tel")] Societe societe)
        {
            if (id != societe.SocieteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(societe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SocieteExists(societe.SocieteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(societe);
        }

        // GET: Societes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var societe = await _context.Societe
                .FirstOrDefaultAsync(m => m.SocieteID == id);
            if (societe == null)
            {
                return NotFound();
            }

            return View(societe);
        }

        // POST: Societes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var societe = await _context.Societe.FindAsync(id);
            if (societe != null)
            {
                _context.Societe.Remove(societe);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SocieteExists(int id)
        {
            return _context.Societe.Any(e => e.SocieteID == id);
        }
    }
}

GSoutenance/Views/Societes/Create.cshtml
@model GSoutenance.Models.Societe

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Societe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LibSociete" class="control-label"></label>
                <input asp-for="LibSociete" class="form-control" />
                <span asp-validation-for="LibSociete" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Societes/Delete.cshtml
@model GSoutenance.Models.Societe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Societe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LibSociete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LibSociete)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SocieteID" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
    </form>
</div>

GSoutenance/Views/Societes/Details.cshtml
@model GSoutenance.Models.Societe

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Societe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LibSociete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LibSociete)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
    </dl>
</div>
<div style="margin-top: 20px;"> 
    <a asp-action="Edit" asp-route-id="@Model?.SocieteID" class="btn btn-outline-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

GSoutenance/Views/Societes/Edit.cshtml
@model GSoutenance.Models.Societe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Societe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SocieteID" />
            <div class="form-group">
                <label asp-for="LibSociete" class="control-label"></label>
                <input asp-for="LibSociete" class="form-control" />
                <span asp-validation-for="LibSociete" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input type="submit" value="Save" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 20px;">
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GSoutenance/Views/Societes/Index.cshtml
@model IEnumerable<GSoutenance.Models.Societe>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">Table Des Societe</h1>

<form asp-controller="Societes" asp-action="Search" method="get" class="d-flex search-from">
    <input class="form-control" type="text" placeholder="Search" name="searchString">
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<p style="margin-top: 20px;">
    <a asp-action="Create" class="btn btn-outline-secondary">Ajouter NV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SocieteID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LibSociete)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tel)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.SocieteID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibSociete)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tel)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.SocieteID" class="btn btn-info">Modifier</a> |
                    <a asp-action="Details" asp-route-id="@item.SocieteID" class="btn btn-warning">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.SocieteID" class="btn btn-danger">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>